branches:
  only:
  - DEV-966
sudo: required
language: java
jdk:
- openjdk8
services:
- docker
env:
- PIPELINE5_VERSION=5.5.$TRAVIS_BUILD_NUMBER
script:
- 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then mvn clean install -B; else mvn clean install -DskipDocker -DskipShade -B; fi'
before_install:
- openssl aes-256-cbc -K $encrypted_7b504d6f794c_key -iv $encrypted_7b504d6f794c_iv
  -in cluster/google-key.json.enc -out cluster/google-key.json -d
- openssl aes-256-cbc -K $encrypted_965d6303826d_key -iv $encrypted_965d6303826d_iv
  -in cluster/src/test/resources/smoke_test/api.jks.enc -out cluster/src/test/resources/smoke_test/api.jks -d
- echo "$DOCKER_HUB_PASSWORD" | docker login -u "hartwigmedicalfoundation" --password-stdin
- mvn versions:set -DnewVersion=$PIPELINE5_VERSION
- sudo apt-get -qq update
- sudo apt-get install -y samtools google-cloud-sdk
- curl https://downloads.rclone.org/v1.48.0/rclone-v1.48.0-linux-amd64.deb --output rclone-current-linux-amd64.deb
- sudo dpkg -i rclone-current-linux-amd64.deb
- "./travis-init.sh"
- export PATH=$PATH:$PWD/bwa/
install: "/bin/true"
after_success:
- docker push hartwigmedicalfoundation/pipeline5:$PIPELINE5_VERSION
