sudo: required
language: java

services:
  - docker

env:
  - PIPELINE5_VERSION=5.1.$TRAVIS_BUILD_NUMBER

script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn clean install -B || mvn clean install -DskipDocker -B'

before_install:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "hartwigmedicalfoundation" --password-stdin
  - mvn versions:set -DnewVersion=$PIPELINE5_VERSION
  - sudo apt-get -qq update
  - sudo apt-get install -y samtools
  - ./travis-init.sh
  - export PATH=$PATH:$PWD/bwa/

install: /bin/true

after_success:
  - docker push hartwigmedicalfoundation/pipeline5:$PIPELINE5_VERSION