sudo: required
language: java

services:
  - docker

env:
  - PIPELINE5_VERSION=5.0.$TRAVIS_BUILD_NUMBER

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y bwa
  - echo "hmf123" | docker login -u "hartwigmedicalfoundation" --password-stdin
  - mvn versions:set -DnewVersion=$PIPELINE5_VERSION

after_success:
  - docker push hartwigmedicalfoundation/pipeline5:$PIPELINE5_VERSION